# Site settings
title: Feedpresso Blog
email: hello@feedpresso.com
description: |-
  Journal of a Startup
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.feedpresso.com" # the base hostname & protocol for your site
paginate: 5
# Build settings
markdown: kramdown
