# Site settings
title: Feedpresso Blog
email: hello@feedpresso.com
description: > # this means to ignore newlines until "baseurl:"
  Journal of a Startup
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.feedpresso.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
